name: Build

on:
  schedule:
    - cron: "0 5 * * 1"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v3

      - name: Setup Docker BuildX Instance
        uses: docker/setup-buildx-action@v2

      - name: Generate app tags
        uses: docker/metadata-action@v4
        id: tags-app
        with:
          bake-target: app
          images: |
            ghcr.io/${{ github.repository }}-app
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/0.') }}

      - name: Generate web tags
        uses: docker/metadata-action@v4
        id: tags-web
        with:
          bake-target: web
          images: |
            ghcr.io/${{ github.repository }}-web
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/0.') }}

      - name: Generate cache tag for app image
        uses: docker/metadata-action@v4
        id: cache-app
        with:
          images: |
            ghcr.io/${{ github.repository }}-app
          tags: |
            type=ref,event=branch
            type=raw,enable=${{ github.ref_type == 'tag' }},value=${{ github.event.repository.default_branch }}
          flavor:
            suffix=-cache

      - name: Generate cache tag for web image
        uses: docker/metadata-action@v4
        id: cache-web
        with:
          images: |
            ghcr.io/${{ github.repository }}-web
          tags: |
            type=ref,event=branch
            type=raw,enable=${{ github.ref_type == 'tag' }},value=${{ github.event.repository.default_branch }}
          flavor:
            suffix=-cache

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Images
        uses: docker/bake-action@v2.3.0
        with:
          targets: production
          files: |
            ./docker-bake.hcl
            ${{ steps.tags-app.outputs.bake-file }}
            ${{ steps.tags-web.outputs.bake-file }}
          set: |
            app.cache-from=type=registry,ref=${{ steps.cache-app.outputs.tags }}
            app.cache-to=type=registry,ref=${{ steps.cache-app.outputs.tags }},mode=max
            web.cache-from=type=registry,ref=${{ steps.cache-web.outputs.tags }}
            web.cache-to=type=registry,ref=${{ steps.cache-web.outputs.tags }},mode=max
          push: true
