name: CI
on:
  push:
    branches-ignore:
      - "renovate/**"
    tags:
      - "**"
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
  build:
    name: Builds
    uses: ./.github/workflows/builds.yml
    needs:
      - tests
