name: Development
on:
  push:
    branches-ignore:
      - "renovate/**"
    tags:
      - "**"
  workflow_dispatch:

jobs:
  test-app:
    uses: ./.github/workflows/test.yml
  build-images:
    uses: ./.github/workflows/build.yml
    needs:
      - test-app
