name: Review Dog
on:
  pull_request:

jobs:
  code_style:
    name: PHP-CS-Fixer
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Format code with PHP-CS-Fixer
        run: docker compose run --rm dev vendor/bin/php-cs-fixer fix

      - name: ReviewDog
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt
